<?xml version="1.0" ?>
<robot name="sr7e" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find sp_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find sp_description)/urdf/sr7e/sr7e.gazebo.xacro"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="20" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.40" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height" value="0.20" /> <!-- base link height -->

  <!-- Wheels -->
  <property name="wheel_radius" value="0.076" /> 
  <property name="wheel_height" value="0.02" />
  <property name="wheel_mass" value="2.50" /> <!-- in kg-->
    
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.075" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <collision>
      <!--origin xyz="0 0 ${height/2}" rpy="0 0 0"/-->
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <geometry>
	      <!--box size="${width} ${width} ${height}"/-->

	      <box size="0.40 0.40 0.02"/>

      </geometry>
    </collision>
    <visual>
      <!--origin xyz="-0.7 0.5 -0.065" rpy="${M_PI/2} 0 0"/-->
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <geometry>
	      <!--box size="0.40 0.40 0.02"/-->
	      <!--box size="${width} ${width} ${height}"/-->
        <!--mesh filename="package://sp_gazebo/meshes/AMR.STL" scale="0.001 0.001 0.001"/-->
      </geometry>
      <material name="white"/>      
    </visual>

    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (0.32*0.32 + 0.8*0.8)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (0.32*0.32 + 1.0*1.0)}" iyz="0.0"
        izz="${mass / 12.0 * (1.0*1.0 + 0.8*0.8)}"/>
    </inertial>
  </link>

  <joint name="for_multi_agent_joint" type="fixed">
    <parent link="base_link"/>
    <child link="for_multi_agent_link"/>
    <origin xyz="0 0 0.01" rpy="0 0 0"/>
  </joint>

  <link name="for_multi_agent_link">
    <visual>
      <origin xyz="0 0 0.00" rpy="0 0 0"/>
      <geometry>
	      <box size="0.60 0.60 0.1"/>
      </geometry>
      <material name="white"/>      
    </visual>
  </link>


  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.261 0" rpy="${-M_PI*0.5} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.076"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.075"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${wheel_mass / 12.0 * (3*0.076*0.076*0.076 + 0.03*0.03)}" ixy="0.0" ixz="0.0"
              iyy="${wheel_mass / 12.0 * (3*0.076*0.076*0.076 + 0.03*0.03)}" iyz="0.0"
              izz="${wheel_mass / 4.0 * (3*0.076*0.076)}" />     
    </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.261 0" rpy="${-M_PI*0.5} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.076"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.075"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${wheel_mass / 12.0 * (3*0.076*0.076*0.076 + 0.03*0.03)}" ixy="0.0" ixz="0.0"
              iyy="${wheel_mass / 12.0 * (3*0.076*0.076*0.076 + 0.03*0.03)}" iyz="0.0"
              izz="${wheel_mass / 4.0 * (3*0.076*0.076)}" />    
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0"/>
  </joint>
  <link name="imu_link"/>

  <joint name="base_laser_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_laser_link"/>
    <origin xyz="0 0 0.094" rpy="0 0 0"/>
  </joint>
  <link name="base_laser_link"/>

  <joint name="scan_joint1" type="fixed">
    <parent link="base_laser_link"/>
    <child link="base_scan1"/>
    <origin xyz="0.445 -0.340 0" rpy="${M_PI} 0 ${-M_PI/4}"/>
  </joint>

  <joint name="scan_joint2" type="fixed">
    <parent link="base_laser_link"/>
    <child link="base_scan2"/>
    <origin xyz="-0.445 0.340 0" rpy="${M_PI} 0 ${3*M_PI/4}"/>
  </joint>

  <link name="base_scan1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- Origin of this mesh is the focal point of the LIDAR. -->
        <mesh filename="package://sp_gazebo/meshes/sick-lms1xx.dae" />
      </geometry>
    </visual>
    <!--collision>
      <origin xyz="0 0 -0.05" rpy="0 0 0" />
      <geometry>
        <box size="0.105 0.1 0.1" />
      </geometry>
    </collision-->
  </link>

  <link name="base_scan2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!-- Origin of this mesh is the focal point of the LIDAR. -->
        <mesh filename="package://sp_gazebo/meshes/sick-lms1xx.dae" />
      </geometry>
    </visual>
    <!--collision>
      <origin xyz="0 0 -0.05" rpy="0 0 0" />
      <geometry>
        <box size="0.105 0.1 0.1" />
      </geometry>
    </collision-->
  </link>

   <!--xacro:sick_lms1xx  frame="base_scan1" topic="scan_1" sample_size="720" update_rate="50"
               min_angle="-2.35619" max_angle="2.35619" min_range="0.1" max_range="30.0" robot_namespace=""/-->


   <!--xacro:sick_lms1xx  frame="base_scan2" topic="scan_2" sample_size="720" update_rate="50"
               min_angle="-2.35619" max_angle="2.35619" min_range="0.1" max_range="30.0" robot_namespace=""/-->


  <joint name="camera_joint2" type="fixed">
    <parent link="base_link"/>
    <child link="vision_2_link"/>
    <origin xyz="0.568 0.216 -0.012" rpy="0 -0.262 -0.7"/>
  </joint>
  <link name="vision_2_link"/>


  <joint name="camera_joint1" type="fixed">
    <parent link="base_link"/>
    <child link="vision_1_link"/>
    <origin xyz="0.568 -0.216 -0.012" rpy="3.14 -0.262 0.7"/>
  </joint>
  <link name="vision_1_link"/>



  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <property name="caster_f_height" value="0.00" /> 
  <property name="caster_f_radius" value="0.025" /> 
  <property name="caster_f_mass" value="5.0" /> <!-- in kg-->


  <property name="caster_height" value="-0.029" /> 

  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <property name="caster_b_height" value="0.00" /> 
  <property name="caster_b_radius" value="0.025" /> 
  <property name="caster_b_mass" value="5.0" /> <!-- in kg-->

<!--Caster front  -->

  <joint name="caster_front_left_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_front_left_link"/>
      <origin xyz="0.450 0.29 ${caster_height}" rpy="${-M_PI/2} 0 0"/>
      <!-- <origin xyz="0.405 0.30 -0.0275" rpy="${-M_PI/2} 0 0"/> -->
  </joint>


  <link name="caster_front_left_link">
    <visual>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
      <geometry>
	      <sphere radius="${caster_f_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>
        <sphere radius="${caster_f_radius}" />
      </geometry>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
    </collision>      
    <inertial>
      <mass value="${caster_f_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}" ixy="0.0" ixz="0.0"
                iyy="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}"  iyz="0.0" 
                izz="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}"  />
    </inertial>
  </link>

  <!--gazebo reference="caster_front_left_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo-->
  
  <joint name="caster_front_right_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_front_right_link"/>
      <origin xyz="0.450 -0.29 ${caster_height}" rpy="${-M_PI/2} 0 0"/>

      <!-- origin xyz="0.555 -0.29 ${caster_height}" rpy="${-M_PI/2} 0 0"/ -->
  </joint>  

  <link name="caster_front_right_link">
    <visual>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
      <geometry>
	      <sphere radius="${caster_f_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>
        <sphere radius="${caster_f_radius}" />
      </geometry>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
    </collision>      
    <inertial>
      <mass value="${caster_f_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}" ixy="0.0" ixz="0.0"
                iyy="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}"  iyz="0.0" 
                izz="${caster_f_mass / 5 * 2 * caster_f_radius * caster_f_radius}"  />
    </inertial>
  </link>


  <!--gazebo reference="caster_front_right_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo-->
    
  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.450 0.29 ${caster_height}" rpy="${-M_PI/2} 0 0"/>
  </joint>

<!--Caster back  -->
  <link name="caster_back_left_link">
    <visual>
      <origin xyz="0 0.02 0 " rpy="${M_PI/2} 0 0" /> 
      <geometry>
	      <sphere radius="${caster_b_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>
        <sphere radius="${caster_b_radius}" />
      </geometry>
      <origin xyz="0 0.02 0 " rpy="${M_PI/2} 0 0" /> 
    </collision>      
    <inertial>
      <mass value="${caster_b_mass}" />
      <origin xyz="0 0 0" />        
      <inertia ixx="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  ixy="0.0" ixz="0.0"
                iyy="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  iyz="0.0" 
                izz="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  />
    </inertial>
  </link>


  <!--gazebo reference="caster_back_left_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo-->

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.450 -0.29 ${caster_height}" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <visual>
      <origin xyz="0 0.02 0 " rpy="${M_PI/2} 0 0" /> 
      <geometry>
	      <sphere radius="${caster_b_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>
        <sphere radius="${caster_b_radius}" />
      </geometry>
      <origin xyz="0 0.02 0 " rpy="${M_PI/2} 0 0" /> 
    </collision>      
    <inertial>
      <mass value="${caster_b_mass}" />
      <origin xyz="0 0 0" />        
      <inertia ixx="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  ixy="0.0" ixz="0.0"
                iyy="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  iyz="0.0" 
                izz="${caster_b_mass / 5 * 2 * caster_b_radius * caster_b_radius}"  />
    </inertial>
  </link>

  <!--gazebo reference="caster_back_right_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo-->

</robot>

